import React from "react";
import { AppConfig } from "./types";
import {
  FiUser,
  FiTerminal,
  FiBriefcase,
  FiFileText,
  FiMail,
  FiCompass,
  FiCpu,
  FiLayers,
  FiActivity,
  FiAward,
  FiHeart,
  FiBookOpen,
  FiSettings,
} from "react-icons/fi";
import { FaGooglePlay } from "react-icons/fa";
import { HiSparkles } from "react-icons/hi2";
import {
  IoRocketOutline,
  IoGameController,
  IoDiceOutline,
  IoGridOutline,
} from "react-icons/io5";

export const APPS: AppConfig[] = [
  // --- PROJECT APPS (Live on Google Play Store from Resume) ---
  {
    id: "kudmi-matrimony",
    name: "Kudmi Matrimony",
    category: "project",
    projectId: "kudmi-matrimony",
    iconGradient: "from-rose-500 via-pink-600 to-purple-600",
    icon: <FiHeart className="text-white text-3xl" />,
    badge: "500+",
    badgeColor: "bg-rose-500 text-white",
    description: "Matrimony app exclusively for the Kudmi Samaj (500+ installs)",
    defaultWidth: 780,
    defaultHeight: 560,
  },
  {
    id: "jharkhand-ekalyan",
    name: "E-Kalyan Guide",
    category: "project",
    projectId: "jharkhand-ekalyan",
    iconGradient: "from-emerald-500 via-teal-600 to-cyan-600",
    icon: <FiBookOpen className="text-white text-3xl" />,
    badge: "180+",
    badgeColor: "bg-emerald-500 text-white",
    description: "Jharkhand welfare & scholarship scheme information app",
    defaultWidth: 780,
    defaultHeight: 560,
  },
  {
    id: "save-prompts",
    name: "Save Prompts",
    category: "project",
    projectId: "save-prompts",
    iconGradient: "from-violet-500 via-purple-600 to-cyan-500",
    icon: <HiSparkles className="text-white text-3xl" />,
    badge: "97+",
    badgeColor: "bg-violet-500 text-white",
    description: "AI image prompt gallery with one-tap clipboard copy",
    defaultWidth: 780,
    defaultHeight: 560,
  },
  {
    id: "jac-results",
    name: "JAC Results",
    category: "project",
    projectId: "jac-results",
    iconGradient: "from-amber-500 via-orange-500 to-rose-600",
    icon: <FiAward className="text-white text-3xl" />,
    badge: "62+",
    badgeColor: "bg-amber-500 text-black",
    description: "Result-lookup app for Jharkhand Academic Council board exams",
    defaultWidth: 780,
    defaultHeight: 560,
  },
  {
    id: "footimes",
    name: "Footimes",
    category: "project",
    projectId: "footimes",
    iconGradient: "from-blue-500 via-indigo-600 to-cyan-500",
    icon: <FiActivity className="text-white text-3xl" />,
    badge: "31+",
    badgeColor: "bg-blue-500 text-white",
    description: "Live football scores and tournament standings app",
    defaultWidth: 780,
    defaultHeight: 560,
  },

  // --- CORE SYSTEM PORTFOLIO APPS ---
  {
    id: "finder",
    name: "About Me",
    category: "core",
    iconGradient: "from-blue-600 to-cyan-500",
    icon: <FiUser className="text-white text-3xl" />,
    description: "Personal bio, background, education, and full-stack overview",
    defaultWidth: 750,
    defaultHeight: 520,
  },
  {
    id: "appstore",
    name: "Projects Hub",
    category: "core",
    iconGradient: "from-cyan-500 via-blue-600 to-indigo-700",
    icon: <FaGooglePlay className="text-white text-2xl" />,
    badge: "5 Apps",
    badgeColor: "bg-cyan-500 text-black",
    description: "Browse all live Google Play Store mobile apps & web solutions",
    defaultWidth: 840,
    defaultHeight: 600,
  },
  {
    id: "terminal",
    name: "Skills Terminal",
    category: "core",
    iconGradient: "from-zinc-900 to-black border border-white/20",
    icon: <FiTerminal className="text-emerald-400 text-3xl font-mono" />,
    badge: "CLI",
    badgeColor: "bg-emerald-500 text-black",
    description: "Interactive command-line interface & technical skill stack",
    defaultWidth: 720,
    defaultHeight: 480,
  },
  {
    id: "experience",
    name: "Experience",
    category: "core",
    iconGradient: "from-purple-600 via-violet-700 to-indigo-800",
    icon: <FiBriefcase className="text-white text-3xl" />,
    description: "Work history at Aura Ads (Full Stack) & Cheers Digitals",
    defaultWidth: 740,
    defaultHeight: 540,
  },
  {
    id: "resume",
    name: "Resume CV",
    category: "core",
    iconGradient: "from-amber-400 via-orange-500 to-red-500",
    icon: <FiFileText className="text-white text-3xl" />,
    description: "View and download Kartik Mahato's verified PDF resume",
    defaultWidth: 760,
    defaultHeight: 580,
  },
  {
    id: "contact",
    name: "Contact / Mail",
    category: "core",
    iconGradient: "from-sky-500 via-blue-600 to-indigo-600",
    icon: <FiMail className="text-white text-3xl" />,
    badge: "Online",
    badgeColor: "bg-emerald-400 text-black",
    description: "Send direct message, copy email, or connect on LinkedIn",
    defaultWidth: 680,
    defaultHeight: 520,
  },
  {
    id: "games",
    name: "Arcade Games",
    category: "utility",
    iconGradient: "from-fuchsia-600 via-pink-600 to-rose-600",
    icon: <FiCpu className="text-white text-3xl" />,
    description: "Play built-in mini games (Snake, Flappy, Memory, TicTacToe)",
    defaultWidth: 720,
    defaultHeight: 520,
  },
  {
    id: "safari",
    name: "Web Browser",
    category: "utility",
    iconGradient: "from-cyan-400 via-blue-500 to-blue-700",
    icon: <FiCompass className="text-white text-3xl" />,
    description: "Explore portfolio website routes & online links",
    defaultWidth: 800,
    defaultHeight: 540,
  },
  {
    id: "settings",
    name: "System Settings",
    category: "utility",
    iconGradient: "from-zinc-600 via-zinc-700 to-zinc-900 border border-white/20",
    icon: <FiSettings className="text-white text-3xl" />,
    badge: "Theme",
    badgeColor: "bg-cyan-500 text-black",
    description: "Customize wallpaper, theme accent colors, dock magnification & blur",
    defaultWidth: 780,
    defaultHeight: 560,
  },
  // --- INDIVIDUAL ARCADE GAMES ---
  {
    id: "game-flappy",
    name: "Flappy Bird",
    category: "game",
    iconGradient: "from-amber-400 via-orange-500 to-rose-500",
    icon: <IoRocketOutline className="text-white text-3xl" />,
    imageIcon: "/games/flappy.png",
    gameUrl: "/games/flappy",
    badge: "Arcade",
    badgeColor: "bg-amber-400 text-black",
    description: "Fly through endless pipes and beat your high score in neon style",
    defaultWidth: 500,
    defaultHeight: 680,
  },
  {
    id: "game-snake",
    name: "Snake Game",
    category: "game",
    iconGradient: "from-emerald-500 via-green-600 to-teal-700",
    icon: <IoGameController className="text-white text-3xl" />,
    imageIcon: "/games/snake.png",
    gameUrl: "/games/snake",
    badge: "Retro",
    badgeColor: "bg-emerald-500 text-black",
    description: "Survival snake experience in a sleek digital grid",
    defaultWidth: 560,
    defaultHeight: 640,
  },
  {
    id: "game-memory",
    name: "Memory Match",
    category: "game",
    iconGradient: "from-cyan-500 via-blue-600 to-indigo-700",
    icon: <IoDiceOutline className="text-white text-3xl" />,
    imageIcon: "/games/memory.png",
    gameUrl: "/games/memory",
    badge: "Brain",
    badgeColor: "bg-cyan-400 text-black",
    description: "Test your brain and speed by matching glowing card pairs",
    defaultWidth: 640,
    defaultHeight: 600,
  },
  {
    id: "game-tictactoe",
    name: "Tic Tac Toe",
    category: "game",
    iconGradient: "from-violet-600 via-purple-600 to-pink-600",
    icon: <IoGridOutline className="text-white text-3xl" />,
    imageIcon: "/games/tictactoe.png",
    gameUrl: "/games/tictactoe",
    badge: "2-Player",
    badgeColor: "bg-violet-500 text-white",
    description: "Classic 2-player strategy game with a modern neon twist",
    defaultWidth: 520,
    defaultHeight: 580,
  },
];
